# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'paginas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1'

  # Pods for paginas

end
