# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '11_18_challengeFipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 11_18_challengeFipe
pod 'Alamofire'

end
