# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'paginacaoG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'UIScrollView-InfiniteScroll', '~> 1.0.0'

  # Pods for paginacaoG

end
